const HOUR = 3600 * 1000
const MINUTE = 60 * 1000

const at = (hoursAgo = 0, minutes = 0) =>
  new Date(Date.now() - hoursAgo * HOUR - minutes * MINUTE).toISOString()

export const CATEGORIES = [
  'Món chính',
  'Món nước',
  'Ăn phụ',
  'Đồ uống',
  'Chè tráng miệng',
]

export const ACCENTS = [
  { id: 'orange', label: 'Cam', css: 'linear-gradient(140deg, #ffb26b, #ff8a3d)' },
  { id: 'amber', label: 'Hổ phách', css: 'linear-gradient(140deg, #ffd08a, #f5a038)' },
  { id: 'caramel', label: 'Caramel', css: 'linear-gradient(140deg, #e8b48a, #d0884a)' },
  { id: 'peach', label: 'Đào', css: 'linear-gradient(140deg, #f2ad81, #e0713b)' },
  { id: 'flame', label: 'Lửa', css: 'linear-gradient(140deg, #ff9b6b, #e85a2d)' },
  { id: 'mint', label: 'Bạc hà', css: 'linear-gradient(140deg, #a8d8c8, #3e8f6b)' },
  { id: 'berry', label: 'Dâu', css: 'linear-gradient(140deg, #f7b2c6, #d64d7e)' },
  { id: 'grape', label: 'Tím', css: 'linear-gradient(140deg, #c3b6f5, #6a5acd)' },
  { id: 'chili', label: 'Ớt', css: 'linear-gradient(140deg, #ff7a6b, #c0392b)' },
  { id: 'ocean', label: 'Biển', css: 'linear-gradient(140deg, #8fc9f0, #2f7fb5)' },
]

export const ACCENT_MAP = ACCENTS.reduce((map, item) => {
  map[item.id] = item
  return map
}, {})

export const accentOf = (id) => ACCENT_MAP[id] ?? ACCENT_MAP.orange

export const DISH_STATUS = {
  available: { label: 'Đang bán', tone: 'success' },
  unavailable: { label: 'Tạm ngưng', tone: 'muted' },
  runningOut: { label: 'Sắp hết', tone: 'warn' },
}

export const ORDER_STATUS = {
  pending: { label: 'Chờ xác nhận', tone: 'warn', next: 'confirmed' },
  confirmed: { label: 'Đã xác nhận', tone: 'info', next: 'preparing' },
  preparing: { label: 'Đang chế biến', tone: 'brand', next: 'delivering' },
  delivering: { label: 'Đang giao', tone: 'violet', next: 'completed' },
  completed: { label: 'Hoàn thành', tone: 'success', next: null },
  cancelled: { label: 'Đã hủy', tone: 'muted', next: null },
}

export const ORDER_FLOW = [
  'pending',
  'confirmed',
  'preparing',
  'delivering',
  'completed',
]

export const SEED_DISHES = [
  {
    id: 'MH-001',
    name: 'Phở bò đặc biệt',
    category: 'Món nước',
    price: 65000,
    description: 'Nước dùng ninh xương 12 tiếng, thịt bò mềm thơm.',
    accent: 'orange',
    emoji: '🍜',
    status: 'available',
    sold: 320,
    createdAt: at(2400),
  },
  {
    id: 'MH-002',
    name: 'Bún chả Hà Nội',
    category: 'Món nước',
    price: 55000,
    description: 'Chả nướng than hoa, nước mắm chua ngọt chuẩn vị.',
    accent: 'amber',
    emoji: '🍲',
    status: 'available',
    sold: 214,
    createdAt: at(2300),
  },
  {
    id: 'MH-003',
    name: 'Bánh mì que CBM',
    category: 'Ăn phụ',
    price: 30000,
    description: 'Bánh mì giòn, pate trứng, chả lụa đầy đặn.',
    accent: 'caramel',
    emoji: '🥖',
    status: 'available',
    sold: 486,
    createdAt: at(2200),
  },
  {
    id: 'MH-004',
    name: 'Cơm tấm sườn',
    category: 'Món chính',
    price: 60000,
    description: 'Sườn nướng mật ong, bì chả trứng hấp nóng.',
    accent: 'peach',
    emoji: '🍚',
    status: 'available',
    sold: 268,
    createdAt: at(2100),
  },
  {
    id: 'MH-005',
    name: 'Bún bò Huế',
    category: 'Món nước',
    price: 65000,
    description: 'Vị cay nồng đặc trưng, giò heo mềm ngon.',
    accent: 'flame',
    emoji: '🍝',
    status: 'available',
    sold: 192,
    createdAt: at(2000),
  },
  {
    id: 'MH-006',
    name: 'Trà sữa trân châu',
    category: 'Đồ uống',
    price: 35000,
    description: 'Trà ủ tươi, trân châu dẻo, ít đường tuỳ chọn.',
    accent: 'mint',
    emoji: '🧋',
    status: 'available',
    sold: 541,
    createdAt: at(1900),
  },
  {
    id: 'MH-007',
    name: 'Gà nướng mật ong',
    category: 'Món chính',
    price: 145000,
    description: 'Gà ta nướng mật ong, da giòn thịt mềm, ăn kèm rau trộn.',
    accent: 'chili',
    emoji: '🍗',
    status: 'available',
    sold: 134,
    createdAt: at(1800),
  },
  {
    id: 'MH-008',
    name: 'Gỏi cuốn tôm thịt',
    category: 'Ăn phụ',
    price: 45000,
    description: 'Bánh tráng cuốn tôm thịt chua cay, chấm mắm nêm.',
    accent: 'grape',
    emoji: '🥗',
    status: 'runningOut',
    sold: 152,
    createdAt: at(1700),
  },
  {
    id: 'MH-009',
    name: 'Chè đậu đỏ nướng',
    category: 'Chè tráng miệng',
    price: 25000,
    description: 'Đậu đỏ ninh nhừ, nước dừa tươi và bột sắn dẻo.',
    accent: 'berry',
    emoji: '🥭',
    status: 'available',
    sold: 178,
    createdAt: at(1600),
  },
  {
    id: 'MH-010',
    name: 'Combo CBM Family',
    category: 'Món chính',
    price: 320000,
    description: 'Phở bò, bún chả, gà nướng mật ong và 2 phần trà sữa.',
    accent: 'flame',
    emoji: '🍱',
    status: 'available',
    sold: 63,
    createdAt: at(1500),
  },
  {
    id: 'MH-011',
    name: 'Cá kho tộ chua nhẹ',
    category: 'Món chính',
    price: 120000,
    description: 'Cá chép kho tộ, nước sốt đậm đà ăn cơm.',
    accent: 'ocean',
    emoji: '🐟',
    status: 'unavailable',
    sold: 88,
    createdAt: at(1400),
  },
  {
    id: 'MH-012',
    name: 'Nước chanh quất',
    category: 'Đồ uống',
    price: 18000,
    description: 'Chanh tươi, quất, mật ong giải khát.',
    accent: 'mint',
    emoji: '🍋',
    status: 'available',
    sold: 327,
    createdAt: at(1300),
  },
]

export const SEED_ORDERS = [
  {
    id: 'CB-1001',
    customer: 'Nguyễn Thị Mai',
    phone: '0903 221 145',
    address: '128 Nguyễn Thị Minh Khai, Quận 1, TP.HCM',
    items: [
      { name: 'Phở bò đặc biệt', price: 65000, qty: 2 },
      { name: 'Trà sữa trân châu', price: 35000, qty: 2 },
    ],
    shipping: 15000,
    status: 'pending',
    payment: 'cod',
    note: 'Ít hành, thêm chút tiêu nhé shop.',
    createdAt: at(0, 12),
    updatedAt: at(0, 12),
    history: [{ status: 'pending', at: at(0, 12) }],
  },
  {
    id: 'CB-1002',
    customer: 'Trần Quốc Bảo',
    phone: '0987 654 321',
    address: '45 Lý Thường Kiệt, Quận 1, TP.HCM',
    items: [
      { name: 'Combo CBM Family', price: 320000, qty: 1 },
      { name: 'Chè đậu đỏ nướng', price: 25000, qty: 2 },
    ],
    shipping: 0,
    status: 'preparing',
    payment: 'card',
    note: 'Giao sau 18h giúp em.',
    createdAt: at(1, 20),
    updatedAt: at(0, 40),
    history: [
      { status: 'pending', at: at(1, 20) },
      { status: 'confirmed', at: at(1, 5) },
      { status: 'preparing', at: at(0, 40) },
    ],
  },
  {
    id: 'CB-1003',
    customer: 'Lê Hoàng Nam',
    phone: '0912 887 766',
    address: '72 Nguyễn Văn Trỗi, Phu Nhuan, TP.HCM',
    items: [
      { name: 'Bún bò Huế', price: 65000, qty: 1 },
      { name: 'Gỏi cuốn tôm thịt', price: 45000, qty: 1 },
    ],
    shipping: 15000,
    status: 'delivering',
    payment: 'cod',
    note: '',
    createdAt: at(2, 10),
    updatedAt: at(0, 25),
    history: [
      { status: 'pending', at: at(2, 10) },
      { status: 'confirmed', at: at(1, 50) },
      { status: 'preparing', at: at(1, 5) },
      { status: 'delivering', at: at(0, 25) },
    ],
  },
  {
    id: 'CB-1004',
    customer: 'Phạm Thu Hà',
    phone: '0355 909 123',
    address: '210 Hai Bà Trưng, Quận 3, TP.HCM',
    items: [{ name: 'Cơm tấm sườn', price: 60000, qty: 2 }],
    shipping: 15000,
    status: 'completed',
    payment: 'card',
    note: 'Cảm ơn shop nhiều nhé!',
    createdAt: at(26, 0),
    updatedAt: at(24, 0),
    history: [
      { status: 'pending', at: at(26, 0) },
      { status: 'confirmed', at: at(25, 40) },
      { status: 'preparing', at: at(25, 10) },
      { status: 'delivering', at: at(24, 40) },
      { status: 'completed', at: at(24, 0) },
    ],
  },
  {
    id: 'CB-1005',
    customer: 'Đỗ Anh Tuấn',
    phone: '0778 456 111',
    address: '9 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
    items: [
      { name: 'Bánh mì que CBM', price: 30000, qty: 3 },
      { name: 'Nước chanh quất', price: 18000, qty: 3 },
    ],
    shipping: 15000,
    status: 'completed',
    payment: 'cod',
    note: '',
    createdAt: at(28, 0),
    updatedAt: at(27, 0),
    history: [
      { status: 'pending', at: at(28, 0) },
      { status: 'confirmed', at: at(27, 50) },
      { status: 'preparing', at: at(27, 30) },
      { status: 'delivering', at: at(27, 15) },
      { status: 'completed', at: at(27, 0) },
    ],
  },
  {
    id: 'CB-1006',
    customer: 'Vũ Khánh Linh',
    phone: '0968 234 567',
    address: '300 Cách Mạng Tháng 8, Quận 10, TP.HCM',
    items: [
      { name: 'Gà nướng mật ong', price: 145000, qty: 1 },
      { name: 'Bún chả Hà Nội', price: 55000, qty: 1 },
      { name: 'Chè đậu đỏ nướng', price: 25000, qty: 1 },
    ],
    shipping: 25000,
    status: 'cancelled',
    payment: 'cod',
    note: 'Khách hủy, không liên lạc được.',
    createdAt: at(30, 0),
    updatedAt: at(29, 30),
    history: [
      { status: 'pending', at: at(30, 0) },
      { status: 'cancelled', at: at(29, 30) },
    ],
  },
  {
    id: 'CB-1007',
    customer: 'Hoàng Đức Anh',
    phone: '0909 111 222',
    address: '15 Lê Văn Sỹ, Quận 3, TP.HCM',
    items: [
      { name: 'Combo CBM Family', price: 320000, qty: 1 },
    ],
    shipping: 0,
    status: 'confirmed',
    payment: 'card',
    note: 'Gọi trước khi giao.',
    createdAt: at(3, 5),
    updatedAt: at(2, 30),
    history: [
      { status: 'pending', at: at(3, 5) },
      { status: 'confirmed', at: at(2, 30) },
    ],
  },
  {
    id: 'CB-1008',
    customer: 'Bùi Thị Hồng Vân',
    phone: '0932 555 888',
    address: '88 Cách Mạng Tháng 8, Quận 5, TP.HCM',
    items: [
      { name: 'Bánh mì que CBM', price: 30000, qty: 2 },
      { name: 'Trà sữa trân châu', price: 35000, qty: 1 },
    ],
    shipping: 15000,
    status: 'completed',
    payment: 'cod',
    note: '',
    createdAt: at(49, 0),
    updatedAt: at(48, 0),
    history: [
      { status: 'pending', at: at(49, 0) },
      { status: 'confirmed', at: at(48, 50) },
      { status: 'preparing', at: at(48, 30) },
      { status: 'delivering', at: at(48, 15) },
      { status: 'completed', at: at(48, 0) },
    ],
  },
  {
    id: 'CB-1009',
    customer: 'Đặng Minh Quân',
    phone: '0812 345 678',
    address: '51 Trần Hưng Đạo, Quận 1, TP.HCM',
    items: [
      { name: 'Phở bò đặc biệt', price: 65000, qty: 1 },
      { name: 'Cá kho tộ chua nhẹ', price: 120000, qty: 1 },
    ],
    shipping: 20000,
    status: 'completed',
    payment: 'card',
    note: 'Không ăn hành.',
    createdAt: at(51, 0),
    updatedAt: at(50, 0),
    history: [
      { status: 'pending', at: at(51, 0) },
      { status: 'confirmed', at: at(50, 50) },
      { status: 'preparing', at: at(50, 30) },
      { status: 'delivering', at: at(50, 20) },
      { status: 'completed', at: at(50, 0) },
    ],
  },
  {
    id: 'CB-1010',
    customer: 'Ngô Bảo Châu',
    phone: '0975 444 333',
    address: '160 Điện Biên Phủ, Quận 3, TP.HCM',
    items: [
      { name: 'Bún bò Huế', price: 65000, qty: 2 },
      { name: 'Nước chanh quất', price: 18000, qty: 2 },
    ],
    shipping: 15000,
    status: 'completed',
    payment: 'cod',
    note: '',
    createdAt: at(74, 0),
    updatedAt: at(73, 0),
    history: [
      { status: 'pending', at: at(74, 0) },
      { status: 'confirmed', at: at(73, 50) },
      { status: 'preparing', at: at(73, 30) },
      { status: 'delivering', at: at(73, 15) },
      { status: 'completed', at: at(73, 0) },
    ],
  },
]
