const HOUR = 3600 * 1000
const MINUTE = 60 * 1000

const at = (hoursAgo = 0, minutes = 0) =>
  new Date(Date.now() - hoursAgo * HOUR - minutes * MINUTE).toISOString()

export const SHIPPING_FEE = 15000
export const FREE_SHIPPING_THRESHOLD = 200000
export const MAX_QTY_PER_ITEM = 20

export const SEED_ADMIN = {
  name: 'Quản trị viên',
  email: 'admin@cbmfood.vn',
  phone: '0900123456',
  password: 'admin123',
}

export const CATEGORIES = [
  'Cơm & Bún',
  'Fast Food',
  'Trà sữa & Đồ uống',
  'Ăn vặt',
  'Healthy',
]

export const CATEGORY_META = {
  'Cơm & Bún': { emoji: '🍚', hint: 'Cơm tấm, bún, phở nước' },
  'Fast Food': { emoji: '🍔', hint: 'Ăn nhanh, nhiều đồ ăn trẻ' },
  'Trà sữa & Đồ uống': { emoji: '🧋', hint: 'Trà sữa, nước ngọt giải khát' },
  'Ăn vặt': { emoji: '🍟', hint: 'Món ăn vặt, khai vị' },
  Healthy: { emoji: '🥗', hint: 'Ít dầu mỡ, giàu dinh dưỡng' },
}

export const DISH_TAGS = {
  banchay: { label: 'Bán chạy', tone: 'hot' },
  freeship: { label: 'Freeship', tone: 'ship' },
  moi: { label: 'Mới', tone: 'new' },
  cham: { label: 'Đang giảm giá', tone: 'hot' },
}

export const DEFAULT_RATING = 4.8

export const SHOP_INFO = {
  name: 'CBM Food',
  hotline: '1900 1234',
  hotlineDisplay: '1900 1234',
  address: '999 Đường Hoàng Mai, Hoàng Mai, Hà Nội',
  openHours: '08:00 - 22:00',
  openDays: 'Thứ 2 - Chủ nhật',
  deliveryTime: 30,
  defaultLocation: 'Hoàng Mai, Hà Nội',
}

export const LOCATIONS = [
  'Hoàng Mai, Hà Nội',
  'Đống Đa, Hà Nội',
  'Cầu Giấy, Hà Nội',
  'Hoàn Kiếm, Hà Nội',
  'Thanh Xuân, Hà Nội',
  'Hà Đông, Hà Nội',
]

export const ACCENTS = [
  { id: 'orange', label: 'Cam', css: 'linear-gradient(140deg, #ffb26b, #ff8a3d)' },
  { id: 'amber', label: 'Hổ phách', css: 'linear-gradient(140deg, #ffd08a, #f5a038)' },
  { id: 'caramel', label: 'Caramel', css: 'linear-gradient(140deg, #e8b48a, #d0884a)' },
  { id: 'peach', label: 'Đào', css: 'linear-gradient(140deg, #f2ad81, #e0713b)' },
  { id: 'flame', label: 'Lửa', css: 'linear-gradient(140deg, #ff9b6b, #e85a2d)' },
  { id: 'mint', label: 'Bạc hà', css: 'linear-gradient(140deg, #a8d8c8, #3e8f6b)' },
  { id: 'berry', label: 'Dâu', css: 'linear-gradient(140deg, #f7b2c6, #d64d7e)' },
  { id: 'grape', label: 'Tím', css: 'linear-gradient(140deg, #c3b6f5, #6a5acd)' },
  { id: 'chili', label: 'Ớt', css: 'linear-gradient(140deg, #ff7a6b, #c0392b)' },
  { id: 'ocean', label: 'Biển', css: 'linear-gradient(140deg, #8fc9f0, #2f7fb5)' },
]

export const ACCENT_MAP = ACCENTS.reduce((map, item) => {
  map[item.id] = item
  return map
}, {})

export const accentOf = (id) => ACCENT_MAP[id] ?? ACCENT_MAP.orange

export const DISH_STATUS = {
  available: { label: 'Đang bán', tone: 'success' },
  unavailable: { label: 'Tạm ngưng', tone: 'muted' },
  runningOut: { label: 'Sắp hết', tone: 'warn' },
}

export const ORDER_STATUS = {
  pending: { label: 'Chờ xác nhận', tone: 'warn', next: 'confirmed' },
  confirmed: { label: 'Đã xác nhận', tone: 'info', next: 'preparing' },
  preparing: { label: 'Đang chế biến', tone: 'brand', next: 'delivering' },
  delivering: { label: 'Đang giao', tone: 'violet', next: 'completed' },
  completed: { label: 'Hoàn thành', tone: 'success', next: null },
  cancelled: { label: 'Đã hủy', tone: 'muted', next: null },
}

export const ORDER_FLOW = [
  'pending',
  'confirmed',
  'preparing',
  'delivering',
  'completed',
]

export const SEED_DISHES = [
  {
    id: 'MH-001',
    name: "Phở bò đặc biệt",
    category: "Cơm & Bún",
    price: 65000,
    originalPrice: 79000,
    description: "Nước dùng ninh xương 12 tiếng, thịt bò mềm thơm.",
    accent: 'orange',
    emoji: '🍜',
    image: '',
    status: 'available',
    rating: 4.9,
    ratingCount: 1284,
    tags: ['banchay', 'freeship'],
    sold: 320,
    createdAt: at(2400),
  },

  {
    id: 'MH-002',
    name: "Bún chả Hà Nội",
    category: "Cơm & Bún",
    price: 55000,
    originalPrice: 0,
    description: "Chả nướng than hoa, nước mắm chua ngọt chuẩn vị.",
    accent: 'amber',
    emoji: '🍲',
    image: '',
    status: 'available',
    rating: 4.7,
    ratingCount: 862,
    tags: ['freeship'],
    sold: 214,
    createdAt: at(2300),
  },

  {
    id: 'MH-003',
    name: "Bánh mì que CBM",
    category: "Fast Food",
    price: 30000,
    originalPrice: 35000,
    description: "Bánh mì giòn, pate trứng, chả lụa đầy đặn.",
    accent: 'caramel',
    emoji: '🥖',
    image: '',
    status: 'available',
    rating: 4.8,
    ratingCount: 1533,
    tags: ['banchay'],
    sold: 486,
    createdAt: at(2200),
  },

  {
    id: 'MH-004',
    name: "Cơm tấm sườn",
    category: "Cơm & Bún",
    price: 60000,
    originalPrice: 0,
    description: "Sườn nướng mật ong, bì chả trứng hấp nóng.",
    accent: 'peach',
    emoji: '🍚',
    image: '',
    status: 'available',
    rating: 4.6,
    ratingCount: 704,
    tags: [],
    sold: 268,
    createdAt: at(2100),
  },

  {
    id: 'MH-005',
    name: "Bún bò Huế",
    category: "Cơm & Bún",
    price: 65000,
    originalPrice: 75000,
    description: "Vị cay nồng đặc trưng, giò heo mềm ngon.",
    accent: 'flame',
    emoji: '🍝',
    image: '',
    status: 'available',
    rating: 4.9,
    ratingCount: 947,
    tags: ['cham'],
    sold: 192,
    createdAt: at(2000),
  },

  {
    id: 'MH-006',
    name: "Trà sữa trân châu",
    category: "Trà sữa & Đồ uống",
    price: 35000,
    originalPrice: 45000,
    description: "Trà ủ tươi, trân châu dẻo, ít đường tuỳ chọn.",
    accent: 'mint',
    emoji: '🧋',
    image: '',
    status: 'available',
    rating: 4.9,
    ratingCount: 2210,
    tags: ['banchay', 'freeship'],
    sold: 541,
    createdAt: at(1900),
  },

  {
    id: 'MH-007',
    name: "Gà nướng mật ong",
    category: "Cơm & Bún",
    price: 145000,
    originalPrice: 0,
    description: "Gà ta nướng mật ong, da giòn thịt mềm, ăn kèm rau trộn.",
    accent: 'chili',
    emoji: '🍗',
    image: '',
    status: 'available',
    rating: 4.8,
    ratingCount: 512,
    tags: ['freeship'],
    sold: 134,
    createdAt: at(1800),
  },

  {
    id: 'MH-008',
    name: "Gỏi cuốn tôm thịt",
    category: "Ăn vặt",
    price: 45000,
    originalPrice: 0,
    description: "Bánh tráng cuốn tôm thịt chua cay, chấm mắm nêm.",
    accent: 'grape',
    emoji: '🥗',
    image: '',
    status: 'runningOut',
    rating: 4.5,
    ratingCount: 388,
    tags: [],
    sold: 152,
    createdAt: at(1700),
  },

  {
    id: 'MH-009',
    name: "Chè đậu đỏ nướng",
    category: "Ăn vặt",
    price: 25000,
    originalPrice: 30000,
    description: "Đậu đỏ ninh nhừ, nước dừa tươi và bột sắn dẻo.",
    accent: 'berry',
    emoji: '🥭',
    image: '',
    status: 'available',
    rating: 4.7,
    ratingCount: 629,
    tags: [],
    sold: 178,
    createdAt: at(1600),
  },

  {
    id: 'MH-010',
    name: "Combo CBM Family",
    category: "Cơm & Bún",
    price: 320000,
    originalPrice: 395000,
    description: "Phở bò, bún chả, gà nướng mật ong và 2 phần trà sữa.",
    accent: 'flame',
    emoji: '🍱',
    image: '',
    status: 'available',
    rating: 4.9,
    ratingCount: 276,
    tags: ['freeship', 'banchay'],
    sold: 63,
    createdAt: at(1500),
  },

  {
    id: 'MH-011',
    name: "Cá kho tộ chua nhẹ",
    category: "Cơm & Bún",
    price: 120000,
    originalPrice: 0,
    description: "Cá chép kho tộ, nước sốt đậm đà ăn cơm.",
    accent: 'ocean',
    emoji: '🐟',
    image: '',
    status: 'unavailable',
    rating: 4.6,
    ratingCount: 311,
    tags: [],
    sold: 88,
    createdAt: at(1400),
  },

  {
    id: 'MH-012',
    name: "Nước chanh quất",
    category: "Trà sữa & Đồ uống",
    price: 18000,
    originalPrice: 0,
    description: "Chanh tươi, quất, mật ong giải khát.",
    accent: 'mint',
    emoji: '🍋',
    image: '',
    status: 'available',
    rating: 4.6,
    ratingCount: 741,
    tags: [],
    sold: 327,
    createdAt: at(1300),
  },

  {
    id: 'MH-013',
    name: "Pizza phô mai cháy viền",
    category: "Fast Food",
    price: 189000,
    originalPrice: 245000,
    description: "Đế nướng thủ công, phô mai mozzarella và topping đầy đủ.",
    accent: 'chili',
    emoji: '🍕',
    image: '',
    status: 'available',
    rating: 4.8,
    ratingCount: 402,
    tags: ['moi', 'freeship'],
    sold: 96,
    createdAt: at(1200),
  },

  {
    id: 'MH-014',
    name: "Burger gà giòn sốt tiêu",
    category: "Fast Food",
    price: 59000,
    originalPrice: 69000,
    description: "Gà chiên giòn, sốt tiêu cay, rau tươi trong bánh mì mềm.",
    accent: 'amber',
    emoji: '🍔',
    image: '',
    status: 'available',
    rating: 4.7,
    ratingCount: 508,
    tags: ['banchay'],
    sold: 184,
    createdAt: at(1100),
  },

  {
    id: 'MH-015',
    name: "Salad gà thảo mộc",
    category: "Healthy",
    price: 69000,
    originalPrice: 79000,
    description: "Gà ốp nướng, rau trộn, sốt mè rang giàu canxi.",
    accent: 'mint',
    emoji: '🥙',
    image: '',
    status: 'available',
    rating: 4.6,
    ratingCount: 233,
    tags: ['moi'],
    sold: 74,
    createdAt: at(1000),
  },

  {
    id: 'MH-016',
    name: "Cháo yến gà hầm măng",
    category: "Healthy",
    price: 49000,
    originalPrice: 0,
    description: "Cháo nếp nhừ, yến hầm măng, gà ta bổ dưỡng cho buổi sáng.",
    accent: 'caramel',
    emoji: '🥣',
    image: '',
    status: 'available',
    rating: 4.9,
    ratingCount: 176,
    tags: [],
    sold: 58,
    createdAt: at(900),
  },
]

export const SEED_ORDERS = [
  {
    id: 'CB-1001',
    customer: 'Nguyễn Thị Mai',
    phone: '0903 221 145',
    address: '128 Nguyễn Thị Minh Khai, Quận 1, TP.HCM',
    items: [
      { name: 'Phở bò đặc biệt', price: 65000, qty: 2 },
      { name: 'Trà sữa trân châu', price: 35000, qty: 2 },
    ],
    shipping: 15000,
    status: 'pending',
    payment: 'cod',
    note: 'Ít hành, thêm chút tiêu nhé shop.',
    createdAt: at(0, 12),
    updatedAt: at(0, 12),
    history: [{ status: 'pending', at: at(0, 12) }],
  },
  {
    id: 'CB-1002',
    customer: 'Trần Quốc Bảo',
    phone: '0987 654 321',
    address: '45 Lý Thường Kiệt, Quận 1, TP.HCM',
    items: [
      { name: 'Combo CBM Family', price: 320000, qty: 1 },
      { name: 'Chè đậu đỏ nướng', price: 25000, qty: 2 },
    ],
    shipping: 0,
    status: 'preparing',
    payment: 'card',
    note: 'Giao sau 18h giúp em.',
    createdAt: at(1, 20),
    updatedAt: at(0, 40),
    history: [
      { status: 'pending', at: at(1, 20) },
      { status: 'confirmed', at: at(1, 5) },
      { status: 'preparing', at: at(0, 40) },
    ],
  },
  {
    id: 'CB-1003',
    customer: 'Lê Hoàng Nam',
    phone: '0912 887 766',
    address: '72 Nguyễn Văn Trỗi, Phu Nhuan, TP.HCM',
    items: [
      { name: 'Bún bò Huế', price: 65000, qty: 1 },
      { name: 'Gỏi cuốn tôm thịt', price: 45000, qty: 1 },
    ],
    shipping: 15000,
    status: 'delivering',
    payment: 'cod',
    note: '',
    createdAt: at(2, 10),
    updatedAt: at(0, 25),
    history: [
      { status: 'pending', at: at(2, 10) },
      { status: 'confirmed', at: at(1, 50) },
      { status: 'preparing', at: at(1, 5) },
      { status: 'delivering', at: at(0, 25) },
    ],
  },
  {
    id: 'CB-1004',
    customer: 'Phạm Thu Hà',
    phone: '0355 909 123',
    address: '210 Hai Bà Trưng, Quận 3, TP.HCM',
    items: [{ name: 'Cơm tấm sườn', price: 60000, qty: 2 }],
    shipping: 15000,
    status: 'completed',
    payment: 'card',
    note: 'Cảm ơn shop nhiều nhé!',
    createdAt: at(26, 0),
    updatedAt: at(24, 0),
    history: [
      { status: 'pending', at: at(26, 0) },
      { status: 'confirmed', at: at(25, 40) },
      { status: 'preparing', at: at(25, 10) },
      { status: 'delivering', at: at(24, 40) },
      { status: 'completed', at: at(24, 0) },
    ],
  },
  {
    id: 'CB-1005',
    customer: 'Đỗ Anh Tuấn',
    phone: '0778 456 111',
    address: '9 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
    items: [
      { name: 'Bánh mì que CBM', price: 30000, qty: 3 },
      { name: 'Nước chanh quất', price: 18000, qty: 3 },
    ],
    shipping: 15000,
    status: 'completed',
    payment: 'cod',
    note: '',
    createdAt: at(28, 0),
    updatedAt: at(27, 0),
    history: [
      { status: 'pending', at: at(28, 0) },
      { status: 'confirmed', at: at(27, 50) },
      { status: 'preparing', at: at(27, 30) },
      { status: 'delivering', at: at(27, 15) },
      { status: 'completed', at: at(27, 0) },
    ],
  },
  {
    id: 'CB-1006',
    customer: 'Vũ Khánh Linh',
    phone: '0968 234 567',
    address: '300 Cách Mạng Tháng 8, Quận 10, TP.HCM',
    items: [
      { name: 'Gà nướng mật ong', price: 145000, qty: 1 },
      { name: 'Bún chả Hà Nội', price: 55000, qty: 1 },
      { name: 'Chè đậu đỏ nướng', price: 25000, qty: 1 },
    ],
    shipping: 25000,
    status: 'cancelled',
    payment: 'cod',
    note: 'Khách hủy, không liên lạc được.',
    createdAt: at(30, 0),
    updatedAt: at(29, 30),
    history: [
      { status: 'pending', at: at(30, 0) },
      { status: 'cancelled', at: at(29, 30) },
    ],
  },
  {
    id: 'CB-1007',
    customer: 'Hoàng Đức Anh',
    phone: '0909 111 222',
    address: '15 Lê Văn Sỹ, Quận 3, TP.HCM',
    items: [
      { name: 'Combo CBM Family', price: 320000, qty: 1 },
    ],
    shipping: 0,
    status: 'confirmed',
    payment: 'card',
    note: 'Gọi trước khi giao.',
    createdAt: at(3, 5),
    updatedAt: at(2, 30),
    history: [
      { status: 'pending', at: at(3, 5) },
      { status: 'confirmed', at: at(2, 30) },
    ],
  },
  {
    id: 'CB-1008',
    customer: 'Bùi Thị Hồng Vân',
    phone: '0932 555 888',
    address: '88 Cách Mạng Tháng 8, Quận 5, TP.HCM',
    items: [
      { name: 'Bánh mì que CBM', price: 30000, qty: 2 },
      { name: 'Trà sữa trân châu', price: 35000, qty: 1 },
    ],
    shipping: 15000,
    status: 'completed',
    payment: 'cod',
    note: '',
    createdAt: at(49, 0),
    updatedAt: at(48, 0),
    history: [
      { status: 'pending', at: at(49, 0) },
      { status: 'confirmed', at: at(48, 50) },
      { status: 'preparing', at: at(48, 30) },
      { status: 'delivering', at: at(48, 15) },
      { status: 'completed', at: at(48, 0) },
    ],
  },
  {
    id: 'CB-1009',
    customer: 'Đặng Minh Quân',
    phone: '0812 345 678',
    address: '51 Trần Hưng Đạo, Quận 1, TP.HCM',
    items: [
      { name: 'Phở bò đặc biệt', price: 65000, qty: 1 },
      { name: 'Cá kho tộ chua nhẹ', price: 120000, qty: 1 },
    ],
    shipping: 20000,
    status: 'completed',
    payment: 'card',
    note: 'Không ăn hành.',
    createdAt: at(51, 0),
    updatedAt: at(50, 0),
    history: [
      { status: 'pending', at: at(51, 0) },
      { status: 'confirmed', at: at(50, 50) },
      { status: 'preparing', at: at(50, 30) },
      { status: 'delivering', at: at(50, 20) },
      { status: 'completed', at: at(50, 0) },
    ],
  },
  {
    id: 'CB-1010',
    customer: 'Ngô Bảo Châu',
    phone: '0975 444 333',
    address: '160 Điện Biên Phủ, Quận 3, TP.HCM',
    items: [
      { name: 'Bún bò Huế', price: 65000, qty: 2 },
      { name: 'Nước chanh quất', price: 18000, qty: 2 },
    ],
    shipping: 15000,
    status: 'completed',
    payment: 'cod',
    note: '',
    createdAt: at(74, 0),
    updatedAt: at(73, 0),
    history: [
      { status: 'pending', at: at(74, 0) },
      { status: 'confirmed', at: at(73, 50) },
      { status: 'preparing', at: at(73, 30) },
      { status: 'delivering', at: at(73, 15) },
      { status: 'completed', at: at(73, 0) },
    ],
  },
]
